name: Test Python Code with unittest

on:
  workflow_call:

jobs:
  check-env-file:
    name: check environment file
    runs-on: ubuntu-latest
    steps:
      - name: Download env.txt as an artifact
        uses: actions/download-artifact@v3
        with:
          name: environment
      - shell: bash
        run: |
          # Read the commands from the file
          source environment.sh
          # Print the environment variables
          echo $DSCRD_CHNL_GENERAL

  test-python:
    # Name the Job
    name: Test python
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install test dependencies
        run: |
          pip install -r requirements.txt

      - name: Download env.txt as an artifact
        uses: actions/download-artifact@v3
        with:
          name: environment

      - name: run tests
        run: |
          source environment.sh
          python -m unittest discover -v -s src