name: Test Python Code with unittest

on:
  workflow_call:

jobs:
  test-python:
    # Name the Job
    name: Test python
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install test dependencies
        run: |
          pip install -r requirements.txt

      - name: Download environment.sh as an artifact
        uses: actions/download-artifact@v3
        with:
          name: environment

      - name: run tests
        run: |
          source environment.sh
          python -m unittest discover -v -s src